package:
  name: xonsh
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
   path: ../

build:
  script: python setup.py install --conda
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - xonsh = xonsh.main:main

requirements:
  build:
    - python
    - ply
    - setuptools
    - jupyter
  run:
    - python
    - ply
    - prompt_toolkit  # [win]

about:
  home: http://xonsh.org/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-compatible shell.

app:
  entry: xonsh
  icon: ../docs/_static/ascii_conch_part_color.png
