package:
  name: xonsh
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url: ../

build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - xonsh = xonsh.main:main

requirements:
  build:
    - python 3.4
    - ply
  run:
    - python 3.4
    - ply

about:
  home: http://xonsh.org/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-compatible shell.

app:
  entry: xonsh
  icon: ../docs/_static/ascii_conch_part_color.png
