coverage:
  status:
    project:
      default:
        target: auto
        threshold: null
    patch:
      default:
        target: auto
        threshold: null
    changes:
      default:
        target: auto
        threshold: null
