-- A collection of xonsh values for the web-ui
-- This file has been auto-generated by elm-compile.xsh


module XonshData exposing (..)

import Json.Decode as Decode exposing (Decoder, list, string)
import Json.Decode.Pipeline exposing (optional, required)


type alias PromptData =
    { name : String
    , value : String
    , display : String
    }


type alias ColorData =
    { name : String
    , display : String
    }


type alias XontribData =
    { name : String
    , url : String
    , license : String
    , description : String
    }


type alias RemoteData =
    { prompts : List PromptData
    , xontribs : List XontribData
    , colors : List ColorData
    , promptValue : PromptData
    , colorValue : ColorData
    , xontribValue : List String
    }


remoteDataDecoder : Decoder RemoteData
remoteDataDecoder =
    let
        prompts =
            Decode.succeed PromptData
                |> required "name" string
                |> required "value" string
                |> required "display" string

        colors =
            Decode.succeed ColorData
                |> required "name" string
                |> required "display" string

        xontribs =
            Decode.succeed XontribData
                |> required "name" string
                |> required "url" string
                |> required "license" string
                |> required "description" string
    in
    Decode.succeed RemoteData
        |> required "prompts" (list prompts)
        |> required "xontribs" (list xontribs)
        |> required "colors" (list colors)
        |> required "promptValue" prompts
        |> required "colorValue" colors
        |> optional "xontribValue" (list string) []
