-- A collection of xonsh values for the web-ui
-- This file has been auto-generated by elm-compile.xsh
module XonshData exposing (..)

import List
import String


type alias PromptData =
    { name : String
    , value : String
    , display : String
    }

prompts : List PromptData
prompts =
    [ { name = "Default", value = "{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"\">(env) </span><span style=\"color: #007f00; font-weight: bold\">lou@carcolh</span><span style=\"color: #00007f; font-weight: bold\"> ~/snail/stuff</span><span style=\"color: #ff0000; font-weight: bold\"> branch</span><span style=\"\"> </span><span style=\"color: #00007f; font-weight: bold\">$</span><span style=\"\"> </span></code></pre></div>" }
    , { name = "Debian chroot", value = "{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{NO_COLOR}> ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"color: #007f00; font-weight: bold\">lou@carcolh</span><span style=\"color: #00007f; font-weight: bold\"> ~/snail/stuff</span><span style=\"\">&gt; </span></code></pre></div>" }
    , { name = "Minimalist", value = "{BOLD_GREEN}{cwd_base}{NO_COLOR} ) ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"color: #007f00; font-weight: bold\">stuff</span><span style=\"\"> ) </span></code></pre></div>" }
    , { name = "Terlar", value = "{env_name}{BOLD_GREEN}{user}{NO_COLOR}@{hostname}:{BOLD_GREEN}{cwd}{NO_COLOR}|{gitstatus}\n{BOLD_INTENSE_RED}➤{NO_COLOR} ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"\">(env) </span><span style=\"color: #007f00; font-weight: bold\">lou</span><span style=\"\">@carcolh:</span><span style=\"color: #007f00; font-weight: bold\">~/snail/stuff</span><span style=\"\">|</span><span style=\"color: #007f7f\">branch|</span><span style=\"color: #00007f; font-weight: bold\">+2</span><span style=\"\">⚑7\n</span><span style=\"color: #ff0000; font-weight: bold\">➤</span><span style=\"\"> </span></code></pre></div>" }
    , { name = "Default with git status", value = "{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{gitstatus: {}}{NO_COLOR} {BOLD_BLUE}{prompt_end}{NO_COLOR} ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"\">(env) </span><span style=\"color: #007f00; font-weight: bold\">lou@carcolh</span><span style=\"color: #00007f; font-weight: bold\"> ~/snail/stuff</span><span style=\"color: #ff0000; font-weight: bold\"> </span><span style=\"color: #007f7f\">branch|</span><span style=\"color: #00007f; font-weight: bold\">+2</span><span style=\"\">⚑7 </span><span style=\"color: #00007f; font-weight: bold\">$</span><span style=\"\"> </span></code></pre></div>" }
    , { name = "Robbyrussell", value = "{BOLD_INTENSE_RED}➜ {CYAN}{cwd_base} {gitstatus}{NO_COLOR} ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"color: #ff0000; font-weight: bold\">➜ </span><span style=\"color: #007f7f\">stuff branch|</span><span style=\"color: #00007f; font-weight: bold\">+2</span><span style=\"\">⚑7 </span></code></pre></div>" }
    , { name = "Just a Dollar", value = "$ ", display = "<div class=\"highlight\" style=\"background: #ffffff; border-style: solid; border-radius: 5px\"><pre style=\"margin: 0em; padding: 0.5em 0.1em; color: #000000; line-height: 125%\"><span></span><code><span style=\"\">$ </span></code></pre></div>" }
    ]
