name: Check News Item

on:
  pull_request_target:
    branches:
    - main

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check News item
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'requirements/ci.txt'
      - run: pip install -r requirements/ci.txt
      - run: python .github/workflows/check-news.py
        env:
          GITHUB_REF: "${{ env.GITHUB_REF }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_REPOSITORY: "${{ env.GITHUB_REPOSITORY }}"
