name: pytest macos 3.7

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        python-version: [3.7]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: ${{matrix.python-version}}-xonsh-test
          environment-file: ci/environment-${{matrix.python-version}}.yml
          update-conda: true
          python-version: ${{ matrix.python-version }}
          condarc-file: ci/condarc.yml
      - shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          python -m xonsh run-tests.xsh --timeout=240

