name: pytest macos 3.7

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        python-version: [ "3.7" ]
    defaults:
      run:
        shell: bash

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip --version
          python -m pip install -r requirements/tests.txt
          python -m pip install . --no-deps
      - name: Run tests
        run: python -m xonsh run-tests.xsh test -- --timeout=240
